# Find SDL2 libraries with MSYS2 support

function(find_sdl_libraries)
    # Determine MSYS2 paths if in MSYS2 environment
    set(MSYS2_INCLUDE_DIR "")
    set(MSYS2_LIB_DIR "")
    if(DEFINED ENV{MSYSTEM})
        if(EXISTS "/mingw64")
            set(MSYS2_PREFIX "/mingw64")
        elseif(EXISTS "/mingw32")
            set(MSYS2_PREFIX "/mingw32")
        elseif(EXISTS "/ucrt64")
            set(MSYS2_PREFIX "/ucrt64")
        elseif(EXISTS "/clang64")
            set(MSYS2_PREFIX "/clang64")
        else()
            set(MSYS2_PREFIX "/mingw64")
        endif()
        set(MSYS2_INCLUDE_DIR "${MSYS2_PREFIX}/include")
        set(MSYS2_LIB_DIR "${MSYS2_PREFIX}/lib")
    endif()
    
    # Find SDL2 libraries
    find_path(SDL2_INCLUDE_DIR SDL2/SDL.h PATHS ${MSYS2_INCLUDE_DIR} NO_DEFAULT_PATH)
    find_library(SDL2_LIBRARY SDL2 PATHS ${MSYS2_LIB_DIR} NO_DEFAULT_PATH)
    find_library(SDL2_TTF_LIBRARY SDL2_ttf PATHS ${MSYS2_LIB_DIR} NO_DEFAULT_PATH)
    find_library(SDL2_IMAGE_LIBRARY SDL2_image PATHS ${MSYS2_LIB_DIR} NO_DEFAULT_PATH)
    find_library(SDL2_MIXER_LIBRARY SDL2_mixer PATHS ${MSYS2_LIB_DIR} NO_DEFAULT_PATH)
    find_library(SDL2_GFX_LIBRARY SDL2_gfx PATHS ${MSYS2_LIB_DIR} NO_DEFAULT_PATH)
    
    # Fallback to standard system paths if not found in MSYS2
    if(NOT SDL2_INCLUDE_DIR)
        find_path(SDL2_INCLUDE_DIR SDL2/SDL.h)
    endif()
    if(NOT SDL2_LIBRARY)
        find_library(SDL2_LIBRARY SDL2)
    endif()
    if(NOT SDL2_TTF_LIBRARY)
        find_library(SDL2_TTF_LIBRARY SDL2_ttf)
    endif()
    if(NOT SDL2_IMAGE_LIBRARY)
        find_library(SDL2_IMAGE_LIBRARY SDL2_image)
    endif()
    if(NOT SDL2_MIXER_LIBRARY)
        find_library(SDL2_MIXER_LIBRARY SDL2_mixer)
    endif()
    if(NOT SDL2_GFX_LIBRARY)
        find_library(SDL2_GFX_LIBRARY SDL2_gfx)
    endif()
    
    if(NOT SDL2_GFX_LIBRARY)
        message(WARNING "SDL2_gfx not found. Install manually or build from source.")
    endif()
    
    # Set up include directories
    if(SDL2_INCLUDE_DIR)
        target_include_directories(pacman_sdl PRIVATE ${SDL2_INCLUDE_DIR})
        if(EXISTS "${SDL2_INCLUDE_DIR}/SDL2")
            target_include_directories(pacman_sdl PRIVATE "${SDL2_INCLUDE_DIR}/SDL2")
        endif()
    endif()
    
    # Export variables
    set(SDL2_INCLUDE_DIR ${SDL2_INCLUDE_DIR} PARENT_SCOPE)
    set(SDL2_LIBRARY ${SDL2_LIBRARY} PARENT_SCOPE)
    set(SDL2_TTF_LIBRARY ${SDL2_TTF_LIBRARY} PARENT_SCOPE)
    set(SDL2_IMAGE_LIBRARY ${SDL2_IMAGE_LIBRARY} PARENT_SCOPE)
    set(SDL2_MIXER_LIBRARY ${SDL2_MIXER_LIBRARY} PARENT_SCOPE)
    set(SDL2_GFX_LIBRARY ${SDL2_GFX_LIBRARY} PARENT_SCOPE)
endfunction()

